### ISSUE TITLE
Add dependabot

### ISSUE THREAD

**Issue by JeffFessler** [JuliaArrays/LazyGrids.jl#12]
@dlfivefifty can you give me access to the Settings for this repo so that I can add dependabot?
(Or add it yourself if you prefer.)
In all my other repos dependabot has been updating the github action versions and I'd like that to be automatic here too.
I can do merges here but I don't have Security access.

**Comment by dlfivefifty** [comment]
Made you admin! Hopefully thsat's enough

**Comment by JeffFessler** [comment]
Yep - thanks!
